ElasticDemo/Models/BookSearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElasticDemo.Models
{
    public class BookSearchViewModel
    {
        public string Id { get; set; }
        public string Ean { get; set; }
        public string Title { get; set; }

        public string Highlights { get; set; }
        public double Score { get; set; }
    }
}

ElasticDemo/Models/BookViewModel.cs
using Nest;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElasticDemo.Models
{
    public class BookViewModel
    {
        public string Id { get; set; }

        public string Ean { get; set; }

        public string Title { get; set; }

        public string Abstract { get; set; }

        public int Printed { get; set; }

        public DateTime PublishDate { get; set; }
    }
}

ElasticDemo/Models/ErrorViewModel.cs
using System;

namespace ElasticDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ElasticDemo/Controllers/ElasticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nest;
using ElasticDemo.Models;
using ElasticDemo.BusinessLayer;
using ElasticDemo.Common;

namespace ElasticDemo.Controllers
{
    public class ElasticController : Controller
    {
        Uri node;
        ConnectionSettings settings;
        ElasticClient client;

        public ElasticController()
        {
            node = new Uri(address);
            settings = new ConnectionSettings(node);
            settings.DefaultIndex("bookstore");
            client = new ElasticClient(settings);
        }

        public IActionResult Index()
        {
            var books = client.Search<BookDTO>();
            var results = new List<BookViewModel>();

            for (int i = 0; i < books.Documents.Count; i++)
            {
                var document = books.Documents.ElementAt(i);
                var hit = books.Hits.ElementAt(i);

                results.Add(Mapper.MapBook(document, hit));
            }

            return View(results);
        }

        public IActionResult Details(string ean)
        {
            var books = client.Search<BookDTO>(s => s.Query(q => q.Term(t => t.Ean, ean)));
            var result = Mapper.MapBook(books.Documents.Single(), books.Hits.Single());

            return View(result);
        }

        public IActionResult Search(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                return View();
            }

            List<BookSearchViewModel> results = new List<BookSearchViewModel>();

            var books = client.Search<BookDTO>(s => s
            .Query(q => q.Match(m => m.Field(f => f.Abstract).Query(text)))
            .Highlight(h => h.PreTags("<mark>").PostTags("</mark>").Fields(fs => fs.Field(a => a.Abstract))));

            for (int i = 0; i < books.Documents.Count; i++)
            {
                var document = books.Documents.ElementAt(i);
                var hit = books.Hits.ElementAt(i);

                results.Add(Mapper.MapBookSearch(document, hit));
            }

            return View(results);
        }

        #region Connection settings
        private string address = @"http://localhost:9200";
        #endregion
    }
}

ElasticDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ElasticDemo.Models;

namespace ElasticDemo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ElasticDemo/Views/Elastic/Details.cshtml
@model ElasticDemo.Models.BookViewModel
@{
    ViewData["Title"] = "Details";
}
<h2>Details</h2>
<div>
    <h4>BookViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Abstract)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Abstract)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Printed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Printed)
        </dd>
        <dt>
            Publish date@*@Html.DisplayNameFor(model => model.PublishDate)*@
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PublishDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ean)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ean)
        </dd>
    </dl>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ElasticDemo/Views/Elastic/Index.cshtml
@model List<BookViewModel>
@{
    ViewData["Title"] = "Index";
}

<h2>Books</h2>
<table id="bookstable" class="display">
    <thead>
        <tr>
            <th>Title</th>
            <th>Abstract</th>
            <th>Printed</th>
            <th>Publish date</th>
            <th>EAN code</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
            {
            <tr>
                <td>@book.Title</td>
                <td>@book.Abstract</td>
                <td>@book.Printed</td>
                <td>@book.PublishDate</td>
                <td>@book.Ean</td>

                <td>
                    <a href="@Url.Action("Details", "Elastic", new { Ean = book.Ean })" class="btn btn-default">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section css
{
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
}
@section Scripts
{
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#bookstable').DataTable();
        });
    </script>
}

ElasticDemo/Views/Elastic/Search.cshtml
@model List<ElasticDemo.Models.BookSearchViewModel>
@{
    ViewData["Title"] = "Search";
}
<h2>Search</h2>

@using (Html.BeginForm("Search", "Elastic", FormMethod.Get))
{
    <div>
        <input type="text" name="text">
        <input type="submit" class="btn btn-default" value="Search" />
    </div>
}

@if (Model != null)
{
    <table id="searchtable" class="table">
        <thead>
            <tr>
                <th>Relevance</th>
                <th>Title</th>
                <th>Highlights</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Score)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.Raw(item.Highlights)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { Ean = item.Ean }, new { @class = "btn btn-default" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@section css
    {
    <link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/1.10.16/css/jquery.dataTables.css">
}
@section Scripts
    {
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#searchtable').DataTable({
                "order": [[0, "desc"]],
                "searching": false,
                "paging": false,
            });
        });
    </script>
}

ElasticDemo/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ElasticDemo/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ElasticDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

ElasticDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElasticDemo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("css", required: false)
    </head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ElasticDemo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Elastic" asp-action="Index">ElasticSearch</a></li>
                    <li><a asp-area="" asp-controller="Elastic" asp-action="Search">Search engine</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - ElasticDemo</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>